# Generated by Django 4.1.1 on 2022-12-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnails', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('medium', models.ImageField(blank=True, upload_to='medium/')),
                ('large', models.ImageField(blank=True, upload_to='large/')),
                ('grayscale', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
